name: Build and Test
on:
  workflow_call:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  flatpak:
    name: Build and Test with Flatpak
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-49
      options: --privileged
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          manifest-path: de.til7701.PuzzleMoreDays.json
          run-tests: true
          bundle: PuzzleMoreDays.flatpak
      - name: Install Flatpak Builder
        run: |
          flatpak install flathub -y org.flatpak.Builder
      - name: Run Lint on Manifest
        run: |
          flatpak run --command=flatpak-builder-lint org.flatpak.Builder manifest de.til7701.PuzzleMoreDays.json
      - name: Run Lint on Repo
        run: |
          flatpak run --command=flatpak-builder-lint org.flatpak.Builder repo repo
